# Config file for inference
# configs/inference/default.yaml

# General settings
project:
  name: "ai_training_project"
  version: "0.1.0"
  description: "AI training project inference configuration"

# Model settings
model:
  name: "custom_model"
  architecture: "resnet50"
  num_classes: 10
  checkpoint_path: "weights/checkpoints/latest.pt"

# Input settings
input:
  shape: [1, 3, 224, 224]  # [batch_size, channels, height, width]
  normalize: true
  mean: [0.485, 0.456, 0.406]  # ImageNet mean
  std: [0.229, 0.224, 0.225]   # ImageNet std

# Inference settings
inference:
  batch_size: 1
  device: "cuda"  # "cuda" or "cpu"
  precision: "fp32"  # "fp32", "fp16", or "int8"
  threshold: 0.5  # Confidence threshold for predictions

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 60
